### ISSUE TITLE
issue launching docker image: jupyter failed to build

### ISSUE THREAD

**Issue by ljwosborne89** [dotcs/komoot-elk-jupyter#1]
Hi, 

I am trying to replicate however upon spinning up the ELK stack via 'docker-compose up' after some loading time I get the following error:

Service 'jupyter' failed to build: The command '/bin/sh -c pip --no-cache-dir install ipykernel scipy jupyter matplotlib pandas elasticsearch && python -m ipykernel.kernelspec' returned a non-zero code: 1

I have also tried running 'docker-compose build jupyter', but this returned the same error.

Any help here?

Lewis

**Comment by dotcs** [comment]
Hi Lewis, sorry for the delay. I have been in vacation without access to the internet and was unable to address the issue. The reason was that the latest Pandas version is incompatible with the Python 3.4 setup that is used in the Jupyter container. See https://github.com/pandas-dev/pandas/issues/20723 for details. I've updated the `master` branch such that it should work again. If you have still issues feel free to reopen the issue.
